// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoEF.Models;

namespace ToDoEF.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20180629084135_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoEF.Models.Tablegroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TablegroupSet");
                });

            modelBuilder.Entity("ToDoEF.Models.Tablelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateEnd");

                    b.Property<DateTime?>("DateStart");

                    b.Property<string>("TaskName");

                    b.HasKey("Id");

                    b.ToTable("TablelistSet");
                });

            modelBuilder.Entity("ToDoEF.Models.Tablelistgroup", b =>
                {
                    b.Property<int>("TablelistId");

                    b.Property<int>("TablegroupId");

                    b.HasKey("TablelistId", "TablegroupId");

                    b.HasIndex("TablegroupId");

                    b.ToTable("TablelistTablegroup");
                });

            modelBuilder.Entity("ToDoEF.Models.Tablelistgroup", b =>
                {
                    b.HasOne("ToDoEF.Models.Tablelist", "Tablelist")
                        .WithMany("Tablelistgroups")
                        .HasForeignKey("TablegroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ToDoEF.Models.Tablegroup", "Tablegroup")
                        .WithMany("Tablelistgroups")
                        .HasForeignKey("TablelistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
